// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileFieldNames          = builder.RawFieldNames(&File{})
	fileRows                = strings.Join(fileFieldNames, ",")
	fileRowsExpectAutoSet   = strings.Join(stringx.Remove(fileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileRowsWithPlaceHolder = strings.Join(stringx.Remove(fileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFileIdPrefix  = "cache:file:id:"
	cacheFileKeyPrefix = "cache:file:key:"
)

type (
	fileModel interface {
		Insert(ctx context.Context, data *File) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*File, error)
		FindOneByKey(ctx context.Context, key string) (*File, error)
		Update(ctx context.Context, data *File) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFileModel struct {
		sqlc.CachedConn
		table string
	}

	File struct {
		Id        int64     `db:"id"`
		Hash      string    `db:"hash"`
		Key       string    `db:"key"`
		Size      int64     `db:"size"`
		CreateAt  time.Time `db:"create_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newFileModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultFileModel {
	return &defaultFileModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`file`",
	}
}

func (m *defaultFileModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fileIdKey := fmt.Sprintf("%s%v", cacheFileIdPrefix, id)
	fileKeyKey := fmt.Sprintf("%s%v", cacheFileKeyPrefix, data.Key)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fileIdKey, fileKeyKey)
	return err
}

func (m *defaultFileModel) FindOne(ctx context.Context, id int64) (*File, error) {
	fileIdKey := fmt.Sprintf("%s%v", cacheFileIdPrefix, id)
	var resp File
	err := m.QueryRowCtx(ctx, &resp, fileIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileModel) FindOneByKey(ctx context.Context, key string) (*File, error) {
	fileKeyKey := fmt.Sprintf("%s%v", cacheFileKeyPrefix, key)
	var resp File
	err := m.QueryRowIndexCtx(ctx, &resp, fileKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `key` = ? limit 1", fileRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, key); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileModel) Insert(ctx context.Context, data *File) (sql.Result, error) {
	fileIdKey := fmt.Sprintf("%s%v", cacheFileIdPrefix, data.Id)
	fileKeyKey := fmt.Sprintf("%s%v", cacheFileKeyPrefix, data.Key)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, fileRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Hash, data.Key, data.Size)
	}, fileIdKey, fileKeyKey)
	return ret, err
}

func (m *defaultFileModel) Update(ctx context.Context, newData *File) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fileIdKey := fmt.Sprintf("%s%v", cacheFileIdPrefix, data.Id)
	fileKeyKey := fmt.Sprintf("%s%v", cacheFileKeyPrefix, data.Key)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, fileRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Hash, newData.Key, newData.Size, newData.Id)
	}, fileIdKey, fileKeyKey)
	return err
}

func (m *defaultFileModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFileIdPrefix, primary)
}

func (m *defaultFileModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFileModel) tableName() string {
	return m.table
}
